// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_PFxYSqbV-mGrItVjZtB_GkpXTexLJLM',
    appId: '1:630017455610:web:b0476e6ea43809bb0ae043',
    messagingSenderId: '630017455610',
    projectId: 'flutterapps-ce929',
    authDomain: 'flutterapps-ce929.firebaseapp.com',
    storageBucket: 'flutterapps-ce929.appspot.com',
    measurementId: 'G-74F1PGZZTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3SVP3_WrZ9JLVT78vGE0TSVmDUxJf30',
    appId: '1:630017455610:android:0ce9f09feb5f94a30ae043',
    messagingSenderId: '630017455610',
    projectId: 'flutterapps-ce929',
    storageBucket: 'flutterapps-ce929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvUh7nxZFrVEgHuXvrYsc8vQmIRKj6aX8',
    appId: '1:630017455610:ios:8684dc9dd84889700ae043',
    messagingSenderId: '630017455610',
    projectId: 'flutterapps-ce929',
    storageBucket: 'flutterapps-ce929.appspot.com',
    iosClientId: '630017455610-luvodjbratgdhuvpcf06i7d8vg2evdkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.alumni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvUh7nxZFrVEgHuXvrYsc8vQmIRKj6aX8',
    appId: '1:630017455610:ios:8684dc9dd84889700ae043',
    messagingSenderId: '630017455610',
    projectId: 'flutterapps-ce929',
    storageBucket: 'flutterapps-ce929.appspot.com',
    iosClientId: '630017455610-luvodjbratgdhuvpcf06i7d8vg2evdkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.alumni',
  );
}
